### ISSUE TITLE
Sponge Support

### ISSUE THREAD

**Issue by Rsl1122** [Rsl1122/Plan-PlayerAnalytics#559]
Since there are no statistics plugins that support Sponge, this is a great addition to Plan.

With the refactoring done in 4.1.5 this can be easily implemented by implementing Sponge specific listeners, tasks and commands.

### Todo

- AbstractPluginFramework
  - [x] Abstract SubCommand to be compatible with Sponge commands
- [x] Listeners
  - [x] Tested
- Tasks
  - [x] TPS Task

After that Plan should be functional on sponge.

Ore Requirements:

- [x] WebServer disabled by default
- [x] Geolocation disabled by default
