### ISSUE TITLE
Organize database classes

### ISSUE THREAD

**Issue by Rsl1122** [Rsl1122/Plan-PlayerAnalytics#818]
#### Lava flow

Current database class hierarchy is suffering from [Lava flow antipattern](https://sourcemaking.com/antipatterns/lava-flow).

This is because of `SaveOperations`, `FetchOperations` and other similar Interfaces being cumbersome to extend - Leading to 3 files being changed each time an operation is added or removed: the interface, implementation and the actual implementation inside `Table` classes.

In addition, the addition of `PlayerContainer` and `ServerContainer` has lead to the fetch code to be stored in two different places: SQL in Table classes and the creation of the objects inside `SQLFetchOps`.

#### Commit after each query

Currently every INSERT or UPDATE will trigger `commit()` being called (On SQLite & H2 - MySQL has auto-commit enabled).

Better model would be to only commit once per transaction. Current model does not include the concept of transactions in any way, which can lead to partial writes in case of a backup, or a restore.
`rollback()` is never utilized as the result, jeopardizing 'Atomicity' (All or nothing) of ACID

#### Tables don't comply with Single responsibility principle.

Table classes currently do 3 things:

- Hold name information of table schemas
- Create the table
- Execute SQL on the table

#### Lava flow

I would like to split PlayerContainer and ServerContainer related fetch operations to Data-Access-Object like classes.

#### Commit after each query

Change call hierarchy so that concept of transaction exists somewhere on the chain, possibly after #817 each event could be considered a transaction.
Committing to database should be handled by the transaction.

#### Tables don't comply with Single responsibility principle.

See if the transaction model better suits holding the SQL queries, if not search for some solution that does not create too many classes per method that are currently in Tables.

**Comment by Rsl1122** [comment]
Structure that favours responsibility split between classes

![untitled diagram](https://user-images.githubusercontent.com/24460436/50733882-57f9bb80-119e-11e9-851b-d8cdf9643b7a.jpg)

Class | Responsibility
-- | --
DAO | "Getter" for larger objects, such as PlayerContainer, can be used during deprecation of FetchOperations, another name might be appropriate to avoid confusion when DAO is not used for saving.
Transaction | "Setter" for inserting information into the database. can be event based as per #817 
Queries | Classes for static methods that return QueryStatement objects
Table | Table schema information (columns) + create table

Transaction and DAO should handle the database dependency automatically, so that no calls to SQLDB would have to be done manually.

Queries should be split appropriately between classes, for example all big insert statements (those used in backup) could be placed in a single file, while single object insertions could be placed in another.

**Comment by Rsl1122** [comment]
Current package structure

```
com.djrapitops.plan.system.database
└── databases
    ├── operation
    └── sql
        ├── objects
        ├── operation
        ├── patches
        ├── processing
        ├── statements
        └── tables
            └── move
```

Draft for new package structure
```
com.djrapitops.plan.system.db
├── databases
├── access
│   ├── dao
│   └── transactions
├── patches
├── sql
│   ├── queries
│   ├── parsing (renamed from statements)
│   └── tables
└── tasks
```
This means things in following packages will be deprecated & removed (Although rest will be moved under `db`)
```
com.djrapitops.plan.system.database.databases.operation
com.djrapitops.plan.system.database.databases.sql.operation
com.djrapitops.plan.system.database.databases.sql.objects
com.djrapitops.plan.system.database.databases.sql.tables.move
```
---
Use of `com.djrapitops.plan.system.database.databases.sql.statements.Column` interface should be replaced with `public static final String` variables for `PreparedStatement` API compatibility.

**Comment by Rsl1122** [comment]
Completion check list:

- [ ] Operations (other than FetchOperations) do not exist
- [ ] Package structure follows the intended design
- [ ] Responsibility between classes is clear
- [ ] Database interface is usable instead of SQLDB implementations
- [ ] Commits and Rollbacks only happen once per transaction
- [ ] Each instance of a database has their own Transaction ExecutorService to not need tasks, and to execute transactions in order
- [ ] Database errors make sense and DBOpException is not being caught everywhere
- [ ] PlanPluginBridge Updated to fix possible issues

**Comment by Rsl1122** [comment]
Since this issue has been in progress for over 30 days, it is useful to figure out what could be improved to do large refactoring in the future. Self retrospective mid-task if you will.

### Personal notes

- Day after day of doing the same kind of refactoring work (move a method to another place with small changes to semantics) it can become dull.
  - Because of the large size of the task I started doing something else with almost instant gratification, new user interface designing. During the redesign some of the work that still needs to be carried out will be obsolete when the new user interface is implemented. The work still needs to be carried out because otherwise neither will be finished.
- Difficult to optimize parts can be very daunting to refactor. In this issue: Sessions + World Times, Player Kill addition to the Sessions is very difficult to optimize (To not include data for sessions that are not being fetched)
- After a few days out of the code parts of the new code was impossible to traverse, so some more intuitive classification was put in place to not "lose a method".

### Key insights

In the future large refactoring should be done incrementally: In this case the way to access the database is going to change. Instead of doing all of the work by moving everything to the new way of doing things, the new way should first be introduced, and the old way deprecated.

This way it is possible to move pieces of the software to the new access method when needed. If the new access method proves to be worse, too much work will not have been wasted.

Good examples for future changes that should be incremental instead of all-at-once:
- Improving event handling #817 
- Deprecation of the Bukkit-Bungee connection system.

**Comment by Rsl1122** [comment]
Error scope analysis was out of the scope of this issue so it was not performed.
